### ISSUE TITLE
[QUESTION] You cannot add more than 200 tracks on your queue.

### ISSUE THREAD

**Issue by IkenHuub** [JasonZigelbaum/jqbx-issues#124]
"You cannot add more than 200 tracks on your queue. Only 200 tracks were added."

Why?

**Comment by JasonZigelbaum** [comment]
You can get around it by adding tracks manually one by one or by adding
them through Spotify (just drag tracks into your Spotify :: Queue playlist
and hit sync within the app). The 200 limit is there in an effort to
prevent people from adding a playlist with like 10k tracks on there (since
it will cause things to slow down considerably). I should probably raise
the limit to 500. Will likely do that in the future. Let me know if that
explains things.
