### ISSUE TITLE
[Feature] - Add song to top of queue

### ISSUE THREAD

**Issue by lucaciraolo** [JasonZigelbaum/jqbx-issues#182]
It would be really nice to be able to add a song to the front of the queue directly. I often add entire playlists to my queue making it quite long. If I want to play a particular song then I need to add it to the queue, scroll all the way to the bottom and then click move to top which is quite cumbersome. Not sure how difficult it would be to implement this?

**Comment by JasonZigelbaum** [comment]
Hi Luca,

Check your "Queue Settings" on your settings page. You can have it so that songs automatically go to the top of the queue when you add them (same w/ playlists). See screenshot: 

<img width="569" alt="Screen Shot 2019-08-09 at 2 26 51 PM" src="https://user-images.githubusercontent.com/821065/62800644-dd857700-bab1-11e9-9e65-253823b47ce6.png">

**Comment by lucaciraolo** [comment]
Amazing thanks, sorry I didn't see that! Absolutely loving JQBX by the way, very well thought out. I've been looking for something like this for years now and only just came across JQBX!
