### ISSUE TITLE
When a new song stars Spotify switches to a separate device.

### ISSUE THREAD

**Issue by snazzymuffin** [JasonZigelbaum/jqbx-issues#83]
When a new song begins in the room Spotify switches to a different connected device. For me spotify switches from my PC to my Amazon Echo located in my kitchen and I have to switch the device every time on my Spotify client.

**Comment by JasonZigelbaum** [comment]
So this is is because JQBX is connected to your Amazon Echo. Can you try clicking on the devices icon on the top right (it's the icon that looks either like a computer or a phone depending on which device it's connected to). Once you click it, select the device you want to hear audio from- if you want to hear audio from your computer, open Spotify first then it should show up and you can select it. Once it's selected it shouldn't switch back to your Echo after each song.
